name = "fawazalharbi"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "fawaz-db"
database_id = "48bdb38c-e07d-4407-a9c2-33b882b1450f"
