name = "fawazalharbi"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Cloudflare D1 Database Binding
# Replace database_id with your Cloudflare D1 Database ID if using D1
# [[d1_databases]]
# binding = "DB"
# database_name = "fawaz-db"
# database_id = "YOUR_CLOUDFLARE_D1_DATABASE_ID"
